### PR TITLE
[CBRD-25086] Add words for the user convenience in user hosts.

### PR DESCRIPTION
**Pull request by eido5**
http://jira.cubrid.org/browse/CBRD-25086

**Description**

For the user convenience, cubrid.msg and cubrid_hosts.conf should be fixed related with user hosts.

**AS-IS**

Cannot find ("%1$s") in "%2$s". Please check permissions of the file or if there is the hostname.
[Default content of cubrid_host.conf]
          127.0.0.1 localhost

**TO-BE**

Cannot find hostname ("%1$s") in "%2$s". Please check permissions of the file or if there is the hostname.
[Default content of cubrid_host.conf]
          127.0.0.1 localhost
           0.0.0.0 your_hostname

### CODE REVIEW

**Review by kisoo-han — APPROVED** [review]

**Comment by eido5** [comment]
@kisoo-han 
Could we close this PR? 
Because I think at #4844, discussion will be lasted including QA's fix notice and so on.
Could you review the PR at #4844 again? Actually this and that PR are totally same.

**Comment by kisoo-han** [comment]
@eido5 ,
QA team told me that they will fix CI problem by next week.
So, I think we don't need to close this PR and wait until they fix the problem.
After that, we can re-run CI again and expect to pass CI. So, please wait.

**Comment by eido5** [comment]
@kisoo-han 
I see. Thank you.

**Comment by sjkimxxx** [comment]
@eido5
All checks have passed

**Comment by eido5** [comment]
@sjkimxxx 
I checked it.
Thank you!

**Pull request merged**
