### PR TITLE
[CBRD-20460] Not to deallocate the last page of vacuum data

### PR DESCRIPTION
**Pull request by ribram**
http://jira.cubrid.org/browse/CBRD-20460

@eseokoh 
Added some debugging code to get more details on what happens when the issue is reproduced.

### CODE REVIEW

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/query/vacuum.c (1 incorrect indentation(s) found)
```
  4515    *    We will deallocate the page and update the first page.
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/query/vacuum.c (1 incorrect indentation(s) found)
```
  4515    *    We will deallocate the page and update the first page.
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/query/vacuum.c (1 incorrect indentation(s) found)
```
  4516    *    We will deallocate the page and update the first page.
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/query/vacuum.c (1 incorrect indentation(s) found)
```
  4527    *    We will deallocate the page and update the first page.
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by eseokoh** [comment]
@ribram 

What a great catch!
Please merge the fix. :)

**Pull request merged**
