### PR TITLE
[CBRD-20377] Fix to recompile threshold for execute query.

### PR DESCRIPTION
**Pull request by razvanradulescu**
http://jira.cubrid.org/browse/CBRD-20377

### CODE REVIEW

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/query/xasl_cache.c (2 incorrect indentation(s) found)
```
   792 	  /* first, mark as deleted, actual delete will occur at xcache_unfix by last unfixer */
   793 	  xcache_entry_mark_deleted (thread_p, *xcache_entry);
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by ribram** [comment]
Question: does recompiler update statistics before recompiling?

**Comment by razvanradulescu** [comment]
The compiler requests the new statistics (xstats_get_statistics_from_server), which updates number of objects and pages for associated files (heap and btree), but the new data is not updated in the catalog (which is performed with xstats_update_statistics).
I think update statistics should be leave as user choice.

**Comment by eseokoh** [comment]
I agree with Razvan :)

**Pull request merged**
