### PR TITLE
[CBRD-20449](2) Fix bad error handling from #199

### PR DESCRIPTION
**Pull request by andrei14vl**
Fix the mistake introduced from the actual fix of CBRD-20449.

### CODE REVIEW

**Comment by eseokoh** [comment]
@andrei14vl 

We may have to consider `ER_HEAP_UNKNOWN_OBJECT` error of `heap_prepare_object_page`. 
Would you examine it?

**Comment by eseokoh** [comment]
@andrei14vl 

The update looks good to me. 
Thank you. :)

**Comment by andrei14vl** [comment]
Great, I will test for regressions and merge right after :smiley:.
Thank you!

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/query/query_opfunc.c (1 incorrect indentation(s) found)
```
  8758       ASSERT_ERROR_AND_SET (err);
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Pull request merged**
