### PR TITLE
[CBRD-20423] add broker math library link information to broker/CMakeLists.txt

### PR DESCRIPTION
**Pull request by gwangil-choi**
when you build with cubridmanager/server it occurs error like below
...
...
[ 78%] Built target unittests_area
[ 78%] Built target unittests_cqueue
[ 78%] Built target unittests_lf
[ 78%] Built target unittests_snapshot
[ 79%] Built target unloaddb
Linking C executable broker_changer
/usr/bin/ld: CMakeFiles/broker_changer.dir/__/src/broker/broker_admin_pub.c.o: undefined reference to symbol 'log10@@GLIBC_2.2.5'
/usr/bin/ld: note: 'log10@@GLIBC_2.2.5' is defined in DSO /lib64/libm.so.6 so try adding it to the linker command line
/lib64/libm.so.6: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make[2]: *** [broker/broker_changer] Error 1
make[1]: *** [broker/CMakeFiles/broker_changer.dir/all] Error 2
make: *** [all] Error 2

gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

cmake --version
cmake version 2.8.11

lsb_release -a
LSB Version: :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description: CentOS Linux release 7.2.1511 (Core)
Release: 7.2.1511
Codename: Core

### CODE REVIEW

**Comment by xkyu** [comment]
@gwangil-choi 
I guess there was some change for DSO linking behavior in CentOS7. So, the math library need to be appended to linker option explicitly.
Anyway, Did you check the patch work properly on Windows OS and earlier version of CentOS too?

**Comment by gwangil-choi** [comment]
@xkyu  It works properly in CentOS 6.7 but other Windows OS, I have no envrionment. 
would you please check on other OSes?

**Comment by xkyu** [comment]
@gwangil-choi 
Windows build will be failed because the m.lib library file does not exist on Windows.

**Comment by gwangil-choi** [comment]
@xkyu  but I added math library only outside of WIN32, I think  it does not affect for  windows building 
what do you think about?

**Comment by xkyu** [comment]
@gwangil-choi No, your patched lines affects windows build.
and it'd be better to find math library using find_library() first and append the library if it exists.

**Comment by gwangil-choi** [comment]
@xkyu  Ok.  I will try to check again.  thank for comments.

**Pull request closed without merging**
