### PR TITLE
[CBRD-20159] Introduced "query execution with commit"

### PR DESCRIPTION
**Pull request by alexstanro**
http://jira.cubrid.org/browse/CBRD-20159

### CODE REVIEW

**Comment by eseokoh** [comment]
@alexstanro 

You told, 
> only one select command is executed
> If the result list file contains more than one page, the query can't be executed with commit.

Please let me ask you reasons on such restrictions.

**Comment by alexstanro** [comment]
When ending query on server side, the list file is destroyed.
 So, the client can't access the other list file pages, except the first one 
 (the first page is returned with "execute query with commit" request, the remaining are obtained with other server requests).
 Probably in most of the cases, the list file contains only one page.

**Comment by alexstanro** [comment]
I found possible inconsistencies on CAS when many queries are executed once with auto-comit and at least one is select. For safety reason, I disabled the optimization on that case.

**Comment by eseokoh** [comment]
@alexstanro 

I don't think the cursors are closed during commit. A cursor should be kept as holdable cursor. 
Please look at `qmgr_clear_trans_wakeup`. 

```C
  while (query_p)
    {
      if (query_p->is_holdable)
        {
          if (is_abort || is_tran_died)
            {
              /* Make sure query entry info is not leaked in session. */
              xsession_clear_query_entry_info (thread_p, query_p->query_id);
            }
          else
            {
              /* this is a commit and we have to add the result to the holdable queries list. */
              if (query_p->query_status != QUERY_COMPLETED)
                {
                  er_log_debug (ARG_FILE_LINE, "query %d not completed !\n", query_p->query_id);
                }
              else
                {
                  er_log_debug (ARG_FILE_LINE, "query %d is completed!\n", query_p->query_id);
                }
              xsession_store_query_entry_info (thread_p, query_p);
              /* reset result info */
              query_p->list_id = NULL;
              query_p->temp_vfid = NULL;
            }
        }
```

If you know a case that a cursor is closed, that must be a bug which should be fixed.

**Comment by alexstanro** [comment]
The code in qmgr_clear_trans_wakeup is meant to add the result to session. The result is used by the next transaction, when explicit commit is used for holdable queries.

The current code does not uses the optimization, if the result list file contains more than one page. If the result contains more than one page, probably the optimization would not be so important, since several requests are needed to server for fetching the remaining pages.

I suppose that if we have only one page in result, the server may safety destroy the result, even for holdable queries. That's because the only page of the result is returned with the request, so the broker does not need to use other server requests for fetching other pages.

So, the execution on server side, for current optimization, is as follow (in this order):
 - execute query
 - end query (destroy the result)
 - commit
So, currently, commit is executed only after query ending.
 
If we want to extend the optimization for queries having many pages into result list file, the execution on server side, must be adapted to allow:
 - execute query
 - commit 
I will try to adapt the code for this extension.

**Comment by eseokoh** [comment]
@alexstanro 

Would you resolve the conflicts?

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/communication/network_interface_sr.c (1 incorrect indentation(s) found)
```
  5227     }
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/communication/network_interface_sr.c (1 incorrect indentation(s) found)
```
  5227     }
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Pull request closed without merging**
