### PR TITLE
[CBRD-24162] Fix logical operation || to && on vacuum_data_page::is_index_valid function

### PR DESCRIPTION
**Pull request by bigpel66**
http://jira.cubrid.org/browse/CBRD-24162

Purpose
`Correct Error` 
Fix logical operation || to && on vacuum_data_page::is_index_valid function on src/query/vacuum.c

Implementation
```c
bool
vacuum_data_page::is_index_valid (INT16 index) const
{
        return index >= index_unvacuumed || index < index_free;
}
```

to

```c
bool
vacuum_data_page::is_index_valid (INT16 index) const
{
        return index >= index_unvacuumed && index < index_free;
}
```

Remarks
N/A

### CODE REVIEW

**Comment by bigpel66** [comment]
@hornetmj @wrlawodms @joohok @eido5 

[CBRD-24162] Waiting for a Code Review

**Comment by wrlawodms** [comment]
@bigpel66 Thank you for the contribution. Please assign reviewers in the top-right-hand corner to run the review process.

**Comment by bigpel66** [comment]
Is it possible to change the reviewers in the top-right corner?
I'm trying to click the area to change the reviewers, but nothing happens.

**Comment by wrlawodms** [comment]
@bigpel66  You could add reviewers with the gear button next to `Reviewers`. Tell me if you can't. I'm not sure, but there might be an authorization issue.
image

**Comment by bigpel66** [comment]
As you've said, I think it has an authorization issue. There's no gear button showing for me.

image

**Comment by wrlawodms** [comment]
@bigpel66 OK, I have added reviewers for this PR. Welcome to CUBRID :)

**Comment by bigpel66** [comment]
Thank you for assigning reviewers for me!

**Review by wrlawodms — APPROVED** [review]

**Review by hornetmj — APPROVED** [review]

**Comment by hornetmj** [comment]
@bigpel66 Please fill in the Purpose field simply.

**Comment by bigpel66** [comment]
Is the form like 'Correct Error' for purpose okay?

**Comment by hornetmj** [comment]
@bigpel66 It seems to be more accurate for the purpose to describe which bugs have been fixed. (You can use the PR title as it is.)

**Comment by bigpel66** [comment]
I've just fixed as you've mentioned! Thank you.

**Review by joohok — APPROVED** [review]

**Review by eido5 — APPROVED** [review]

**Pull request merged**
