### PR TITLE
[CBRD-23925] When used as a function parameter, the original pointer variable is not initialized to NULL.

### PR DESCRIPTION
**Pull request by youngjinj**
http://jira.cubrid.org/browse/CBRD-23925

Purpose
- When initializing a pointer variable used as a parameter of a function to NULL, modify the original pointer variable to be initialized to NULL.

Implementation
- I changed the following two functions to macro functions.
  * src/query/cursor.c: cursor_free_list_id(), cursor_free_self_list_id()

Remarks
- N/A

### CODE REVIEW

**Review by byungwook-kim — APPROVED** [review]

**Review by ctshim — COMMENTED** [review]
If you just modify the function's parameter declaration as shown below, it seems that you can get the same result as the current modification without modifying any other code at all.

```
void
cursor_free_list_id (QFILE_LIST_ID*  &list_id_p, bool self)

void
cursor_free_self_list_id (QFILE_LIST_ID* &list_id)
```

**Review by shparkcubrid — APPROVED** [review]

**Review by ctshim — COMMENTED** [review]
Consider also changing the cursor_free_self_list_id() function to a macro like the one below.
I think I can minimize code changes this way
```

#define cursor_free_self_list_id(p) do {        \
        if((p)) {                               \
                cursor_free_list_id (list_id, true);  \
                list_id = NULL;                 \
        }                                       \
    } while(0)

```

**Review by ctshim — APPROVED** [review]
There seems to be no problem with the code apart from the comments I gave.

**Review by hgryoo — APPROVED** [review]

**Comment by ctshim** [comment]
When trying to process using & in the parameter, I found that if type casting is needed, you can use reinterpret_cast.
See fnxx( **_reinterpret_cast<int*&>(pv)_** ); in the code below.

```
void fnxx(int* & pi)
{
        if(pi)
            free(pi);

        pi = (int*) malloc(32);
        pi[0] = 7;
}

void test()
{
        void* pv = (void*) malloc(64);
  
        printf("%08x\n", pv);
        fnxx( reinterpret_cast<int*&>(pv) );
        printf("%08x   %d\n",  pv, ((int*)pv)[0]);
}
```

Result)
```
00607010
00607060   7
```

**Comment by youngjinj** [comment]
@ctshim

As you commented on, I want to change it to a macro function.

Both functions are not complex functions.
I agree that it is better to avoid unnecessary function calls and casting to double pointer variables.

However, it is different from the original PR content, so I will ask other people to review it again.

**Review by shparkcubrid — APPROVED** [review]

**Review by hgryoo — APPROVED** [review]

**Review by ctshim — APPROVED** [review]

**Review by byungwook-kim — APPROVED** [review]

**Pull request merged**
