### PR TITLE
[CBRD-25108] Correct misclassifications in the file tracker.

### PR DESCRIPTION
**Pull request by hyahong**
http://jira.cubrid.org/browse/CBRD-25108

Purpose
re-categorize the types of files.

Implementation
N/A

Remarks
N/A

### CODE REVIEW

**Review by hornetmj — APPROVED** [review]

**Review by wrlawodms — APPROVED** [review]

**Comment by joohok** [comment]
Is it okay not to handle `FILE_TEMP`?
While `SPACEDB_TEMP_FILE` is already being processed in `file_spacedb()`,
if we don't handle the `FILE_TEMP` case here, the usage of `FILE_TEMP` may also be considered as SYSTEM.

so I think it can be, 
SPACEDB_SYSTEM_FILE = system files + FILE_TEMP
SPACEDB_TEMP_FILE = FILE_TEMP

**Comment by wrlawodms** [comment]
@joohok As far as I know, only permanent files are registered in the `file_tracker`.

In `file_create()`,
```
 3808
 3809   if (!is_temp && file_type != FILE_TRACKER)
 3810     {
 3811       /* add to tracker */
 3812       error_code = file_tracker_register (thread_p, vfid, file_type, NULL);
 3813       if (error_code != NO_ERROR)
 3814         {
 3815           ASSERT_ERROR ();
 3816           goto exit;
 3817         }
 3818     }
```

**Comment by joohok** [comment]
> @joohok As far as I know, only permanent files are registered in the `file_tracker`.
> 
> In `file_create()`,
> 
> ```
>  3808
>  3809   if (!is_temp && file_type != FILE_TRACKER)
>  3810     {
>  3811       /* add to tracker */
>  3812       error_code = file_tracker_register (thread_p, vfid, file_type, NULL);
>  3813       if (error_code != NO_ERROR)
>  3814         {
>  3815           ASSERT_ERROR ();
>  3816           goto exit;
>  3817         }
>  3818     }
> ```

Thanks!

**Review by joohok — APPROVED** [review]

**Comment by hornetmj** [comment]
@hyahong rebase your code to fix test_sql_ol failure.

**Review by Rudeus — APPROVED** [review]

**Comment by hyahong** [comment]
@hornetmj  I performed a rebase

**Pull request merged**
