### PR TITLE
[CBRD-22812] Add java.sql.Driver service provider

### PR DESCRIPTION
**Pull request by quaff**
http://jira.cubrid.org/browse/CBRD-22812

The DriverManager methods getConnection and getDrivers have been enhanced to support the Java SE Service Provider mechanism (SPM). According to SPM, a service is defined as a well-known set of interfaces and abstract classes, and a service provider is a specific implementation of a service. It also specifies that the service provider configuration files are stored in the META-INF/services directory. JDBC 4.0 drivers must include the file META-INF/services/java.sql.Driver. This file contains the name of the JDBC driver's implementation of java.sql.Driver.

### CODE REVIEW

**Comment by cubridci** [comment]
Build comment file: 
--------------
**
** This Pull Request's title is 'Add java.sql.Driver service provider'.
** And it does not start with a related JIRA issue number **
** Please edit this Pull Request's title. (eg: '[CBRD-20309] Redesign vacuum data flush' **
**

--------------

**Comment by eseokoh** [comment]
@quaff 

Please refer to 
http://jira.cubrid.org/browse/CBRD-22812?focusedCommentId=4753848&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4753848 for CLA :)

**Comment by quaff** [comment]
@eseokoh can you provide online system like https://cla.pivotal.io/, print or scan is troublesome.

**Comment by eseokoh** [comment]
@quaff 

please refer to http://jira.cubrid.org/browse/CBRD-22812?focusedCommentId=4753853&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4753853

**Comment by eseokoh** [comment]
@quaff 

Thanks for the fix :)

**Pull request merged**
