### PR TITLE
[CBRD-20185] File manager redesign

### PR DESCRIPTION
**Pull request by ribram**
This is work in progress. But I'll open the PR so we can start a conversation during development.

@eseokoh 
I have made some changes to log manager and system operations. The basic idea is to extend the commit system operation to handle complex cases of undo, compensate and run postpone. This is an older idea I had, but that was never implemented. I think the time has come, since I really need it for file manager redesign. The alternative is yet another hackish ways of handling some complex operations on file header and tables (hackish ways that in the end may prove even harder to implement than this).

Please review the changes in the commit fe605f0.

### CODE REVIEW

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/storage/disk_manager.c (1 incorrect indentation(s) found)
```
  3021 	      + cursor->offset_to_unit * DISK_STAB_UNIT_BIT_COUNT + cursor->offset_to_bit == cursor->sectid);
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/storage/disk_manager.c (1 incorrect indentation(s) found)
```
  3021 	      + cursor->offset_to_unit * DISK_STAB_UNIT_BIT_COUNT + cursor->offset_to_bit == cursor->sectid);
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/storage/disk_manager.c (2 incorrect indentation(s) found)
```
  4666 	{
  4668 	}
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/storage/file_manager.c (1 incorrect indentation(s) found)
```
 14232 	      || (file_extdata_is_empty (part_table) && VPID_ISNULL (&part_table->vpid_next)));
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/storage/file_manager.c (4 incorrect indentation(s) found)
```
 20668 	{
 20669 	  ASSERT_ERROR ();
 20670 	  goto exit;
 20671 	}
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/storage/file_manager.c (1 incorrect indentation(s) found)
```
 20500 	    flre_get_tran_num_temp_files (thread_p));
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by eseokoh** [comment]
Please look at `flre_create` and find the case to allocate a new file table page:
```C
          page_ftab = pgbuf_fix (thread_p, &vpid_ftab, NEW_PAGE, PGBUF_LATCH_WRITE, PGBUF_UNCONDITIONAL_LATCH);
          if (page_ftab == NULL)
            {
              ASSERT_ERROR_AND_SET (error_code);
              goto exit;
            }
          pgbuf_set_page_ptype (thread_p, page_ftab, PAGE_FTAB);
          memset (page_ftab, DB_PAGESIZE, 0);
          extdata_part_ftab = (FILE_EXTENSIBLE_DATA *) page_ftab;
          file_extdata_init (sizeof (FILE_PARTIAL_SECTOR), DB_PAGESIZE, extdata_part_ftab);

```

It seems last allocated `page_ftab` may not be set as dirty. When it exits the loop, it will just log and unfix the page.

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/storage/page_buffer.c (2 incorrect indentation(s) found)
```
 12422 #else	/* !SERVER_MODE */		   /* SA_MODE */
 12440 #else	/* !SERVER_MODE */		   /* SA_MODE */
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/storage/page_buffer.c (2 incorrect indentation(s) found)
```
 12422 #else	/* !SERVER_MODE */		   /* SA_MODE */
 12440 #else	/* !SERVER_MODE */		   /* SA_MODE */
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by eseokoh** [comment]
```c
int
disk_auto_expand (THREAD_ENTRY * thread_p)
{   
  int error_code = NO_ERROR;
  
  /* todo: we cannot expand the volumes unless we have a transaction descriptor. we might allocate a special tdes for
   *       auto-volume expansion thread, similar to how vacuum works. otherwise, it can be limited to extend last
   *       volume only.
   * for now, do nothing. we'll think about it later.
   */

  return error_code;
}
```

I think to extend only the last volume would be enough and DBAs expect to extend a volume and create a new one when the last reaches the maximum size.

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/storage/file_manager.c (1 incorrect indentation(s) found)
```
  1755       *page_out = NULL;		/* make it sure for an error */
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Pull request merged**
