### PR TITLE
[CBRD-20233] Fix replication for REC_RELOCATION/REC_NEWHOME records.

### PR DESCRIPTION
**Pull request by razvanradulescu**
Fix replication for REC_RELOCATION/REC_NEWHOME records.

### CODE REVIEW

**Comment by eseokoh** [comment]
@razvanradulescu 

I've considered to remove `RVHF_INSERT_NEWHOME` and use `RVHF_INSERT`, but it seems it does not work. I have not experimented a test. Would you confirm the idea?
I mean to remove `REC_NEWHOME` block from `heap_log_insert_physical`:
```C
      else if (recdes_p->type == REC_NEWHOME)
        {
          /* we don't want replication for REC_NEWHOME; in any other respect RVHF_INSERT_NEWHOME is the same as
           * RVHF_INSERT */
          log_append_undoredo_recdes (thread_p, RVHF_INSERT_NEWHOME, &log_addr, NULL, recdes_p);
        }
```

If you think it will not work, please update the comment:

```C
/* we don't want replication for REC_NEWHOME; ... 
 */
```

**Comment by eseokoh** [comment]
@razvanradulescu 

Please find [a new issue report](http://jira.cubrid.org/browse/CBRD-20266) and confirm your patch fixes it.

**Comment by razvanradulescu** [comment]
Issue CBRD-20266 is not fixed with this patch.
(the error still appear in log_applier)

**Comment by eseokoh** [comment]
@razvanradulescu 

I'm sorry to hear it. Please investigate the new case.

**Comment by razvanradulescu** [comment]
I performed a test replacing RVHF_INSERT_NEWHOME with RVHF_INSERT : does not solve the issue:
log_applier says REC_RELOCATION is not a valid record:
Time: 05/24/16 21:40:51.786 - DEBUG *** file ../src/transaction/log_applier.c, line 4961
apply_update : rectype.type = 4

**Comment by eseokoh** [comment]
@razvanradulescu 

Would you please merge the fix and investigate the new issue as another?
Thank you. 😃

**Pull request merged**
