### PR TITLE
[LETS-724] Define the process types for newHA

### PR DESCRIPTION
**Pull request by joohok**
http://jira.cubrid.org/browse/LETS-724

Purpose

Add process type managed by cub_master
- Transaction Server : HB_PTYPE_TRAN_SERVER
- Page Server : HB_PTYPE_PAGE_SERVER

After removing or replacing all legacy code, 
then I will remove the HB_PTYPE_SERVER, HB_PTYPE_COPYLOGDB, and HB_PTYPE_APPLYLOGDB.

### CODE REVIEW

**Review by hornetmj — APPROVED** [review]

**Review by cristiarg — APPROVED** [review]

**Review by wrlawodms — COMMENTED** [review]
Are the related codes with the process type changed later or just missed?
`hb_type_to_str()`, `hb_pack_server_name()`, `ha_argv_to_args()`, and more (I'm not sure).

**Comment by joohok** [comment]
> Are the related codes with the process type changed later or just missed?
> `hb_type_to_str()`, `hb_pack_server_name()`, `ha_argv_to_args()`, and more (I'm not sure).

I understand what you mean. 

I plan to remove/change the codes related to existing process types at a later stage. 
Since they are still deeply intertwined with the untouched code, I have refrained from making any changes for now. 

It seems that the existing codes will be removed after the following steps are completed:

1. Adding process types. (This PR)
2. Executing the added process types. (Next PR)
   - `hb_pack_server_name ()` may be changed here. (this is called during starting up the process)
3. Implementing the jobs that the process types should perform. (Later)

**Review by wrlawodms — APPROVED** [review]
OK, it makes sense. 
It seems better to change here some codes not for behavior, but for definitions like: `hb_process_type_string()` and `hb_type_to_str()`. at your choice.

**Review by wrlawodms — APPROVED** [review]
OK, it makes sense. 
It seems better to change here some codes not for behavior, but for definitions like: `hb_process_type_string()` and `hb_type_to_str()`, though. at your choice.

**Comment by joohok** [comment]
> OK, it makes sense.
> It seems better to change here some codes not for behavior, but for definitions like: `hb_process_type_string()` and `hb_type_to_str()`, though. at your choice.

OK, thanks.
`hb_type_to_str()` is only called when copylogdb and applylogdb is started. 

I want to focus on where the  `HB_PTYPE_SERVER` is used because it is the part relevant to  the issues. When it becomes possible to remove the parts related to `HB_PTYPE_APPLYLOGDB/COPYLOGDB`, I will proceed with removing the  `hb_type_to_str()`

**Pull request merged**
