### PR TITLE
[CBRD-20143] Vacuum data storage is redesigned as page-based.

### PR DESCRIPTION
**Pull request by ribram**
Details found on http://jira.cubrid.org/browse/CBRD-20143.

Change list:

**Vacuum data**:
Storage is changed to a regular page-based file. The main purpose of this change is to avoid partial-flush issue (flushing continuous areas bigger than 4kb is not guaranteed). Any solution found for the issue will be applicable to page level and it would be hard to adapt to vacuum data. The second important reason is to avoid fixed-size vacuum data. The third reason is to get rid of complicated routines that simulate disk pages for the entire vacuum data.

Vacuum data pages are organized internally as a queue. Each page has a header which includes the link to next page and also two indexes: unvacuumed entry index and free entry index. The rest of the page is filled with vacuum data.
The unvacuumed index points to first data entry in page that was not (yet) vacuumed. The free index points to free area in page where new blocks can be appended.

Accessing vacuum data entries is no longer straight-forward. Pages must be fixed from page buffer, which can be a lot slower than locking one mutex. Therefore, concurrency on vacuum data is unwanted and only vacuum master is allowed to access it. First and last page are always be write-latched by master thread.

New entries are always appended to the free area of last page and a new page is allocated if there is no free space. Generated and finished jobs generally belong to the first page. When all entries in the first page are vacuumed, it is deallocated. We avoid moving data between pages, because it would be costly (system operations are required and a lot more logging). However, allocating and deallocating is also expensive. Even though they cannot always be avoided, as long as there is only a vacuum data page, its space is recycled until it becomes full and we have no other choice but to allocate another page.

Previously, when a worker finished processing a block, it used to mark the block as vacuumed directly in vacuum data. Since workers can no longer access the vacuum data, they use a latch-free circular queue to notify master of the finished jobs. Master then handles marking the blocks and any other necessary changes to vacuum data pages.

**Vacuum data meta-information**:
Besides the vacuum data disk storage, VACUUM_DATA structure is used to store related information in-memory. The meta-information is generally used as a mean of communication between threads in an asynchronous manner.
- vacuum_data_file - is read from boot_Db_parm by boot loader and is used by master to load vacuum data.
- last_blockid - is computed/recovered by master when vacuum data is loaded. it is then used to track the last block added to vacuum data.
NOTE: recovering last_blockid should normally be easy: just get the blockid of last entry in last vacuum data page. However, if vacuum data is empty, there would be no data to read the blockid from. The case is handled by saving last_blockid in what would be first vacuum data entry.
- keep_from_log_pageid - is updated by vacuum master after blocks are marked as vacuumed and is used by archive purger to avoid removing archives necessary for vacuum.
- oldest_unvacuumed_mvccid - is updated by vacuum master and is used to clean dropped files or to check for unvacuumed database entries.
- first_page/last_page - vacuum data pages, used by master each iteration.
- is_loaded - set to true when vacuum data is loaded from disk.
- page_data_max_count - is computed by boot loader and is used by master.
- log_block_npages - is read from boot_Db_parm by boot loader and is used by all threads (active workers to generate log blocks and vacuum threads to prefetch/read log).
- flush_vacuum_data - is set by checkpoint thread to request master flush vacuum data. then it is used by master to notify checkpoint thread when all data has been flushed.
- recovery_lsa - is set by boot loader if server previously crashed and recovery was required. master can then use it as starting point to recover block data buffer.
- is_vacuum_complete - used in stand-alone to mark that vacuum was executed. any further xvacuum calles will just return.

Vacuum master changes:
1. Allocating and deallocating vacuum data pages require system operations. This is the reason that master is also assigned a "vacuum worker" structure, and all system operation and logging code that was used for vacuum workers is extended to master also. The TRID(-2) is now assigned to master, while the range [-3, workers_max_count - 2] to vacuum workers.
NOTE: stand-alone uses only one vacuum worker to handle both master and worker jobs.
2. Because vacuum worker thread can be the only holder for vacuum data first and last page, loading vacuum data and finishing vacuum before shutdown is now the job of master.
3. Processing vacuum data has a few changes:
    - Start job is logged only after it was successfully added to job queue.
    - If a block newest MVCCID is too new or if some of its log records are still in prior node, the entire master iteration is interrupted.
    - Iteration is restarted if block data buffer or finished jobs queue become half-full.
    
Block data buffer recovery:
The implementation was somewhat simplified. Rather than trying to collect relevant information during recovery, the missing blocks are recovered starting with last MVCC operation that can be found and going backwards. Recovering stops when log belonging to last vacuum data block is reached.

Flushing vacuum data:
Because only vacuum master can access vacuum data, checkpoint thread cannot access it to flush. Currently, it notifies vacuum that vacuum data must be flushed and vacuum master executes the flush on its next iteration. Once it finishes, checkpoint is notified back and can continue flushing the rest of the pages.
However, this system has one major drawback: flushing data pages can be slow and can block master for a long time. And vacuum master's iteration should be as short as possible. We need to address this problem too.

Oldest unvacuumed MVCCID:
Processing all vacuum data to find the oldest_unvacuumed_mvccid is not feasible. Oldest block MVCCID's were previously computed strictly from the block's log records. Now it is set to vacuum_Global_oldest_active_mvccid value when first block record is generated. Since vacuum_Global_oldest_active_mvccid value can never decrease, oldest MVCCID of blocks also can never decrease. As a consequence, it is enough to read the oldest MVCCID of first block to estimate the oldest_unvacuumed_mvccid.
Empty vacuum data is a corner case for computing the oldest_unvacuumed_mvccid (there is no first entry to read it from). To cover this case, before consuming blocks from block data buffer, vacuum_Save_log_hdr_oldest_mvccid is read from block currently cached in log_Gl.hdr (the block that is not yet complete). If vacuum data is empty after consuming buffer, this value is used for oldest_unvacuumed_mvccid.

Vacuum worker:
Since vacuum data lock (mutex) has been removed, assigning vacuum worker was no longer protected. In order to avoid assigning same worker structure to two threads, each is assigned an index first (using atomic CAS).

heap_vacuum_all_objects (called by active workers)
1. Call heap_vacuum_all_objects for partition reorganizing (similarly to upgrade domain).
2. Removed the code that changed log_Gl.hdr.last_block_oldest_mvccid and log_Gl.hdr.last_block_newest_mvccid in heap_insert_logical when called for reorganize (unnecessary since vacuum is called before).

Removed code:
1. System parameter for vacuum data size.
2. Save blocks to log and recover them later.
3. Flush and recover vacuum data.
4. Vacuum data mutex.

GDB debugging scripts:
1. updated vacuum_print_entries.
2. created new versions for vacuum_process_log_record and vacuum_print_log_data_on_page that can read its log pages from log page buffer instead of worker prefetched buffer.
3. created new functions vacuum_worker_print_log_block_records and vacuum_print_log_block_records.

Misc:
1. Fixed parsing thrd_holder_info->thrd_hold_list to look for current buffer pointer in pgbuf_flush_page_with_wal.
2. Removed vacuum_is_page_of_vacuum_data from spage_header_start_scan and spage_slots_start_scan.

    
Future work required:
1. Flushing vacuum data: currently, master has to flush all vacuum data. This is not optimum and it can be really bad if vacuum lags behind and vacuum data has many pages.
2. Changing the default vacuum configuration in a way that allows performance benchmark fit all vacuum data in one page.
3. Prevent vacuum data page deallocations.
4. Page buffer for vacuum data.

### CODE REVIEW

**Comment by eseokoh** [comment]
@ribram 
Would you please also change disk_compatibility_level as 10.01f?

**Comment by ribram** [comment]
@eseokoh 
Updated disk_compatibility_level to 10.01f.

**Comment by eseokoh** [comment]
@ribram 
It looks great. You can merge your patch when you want. 
Do you want to wait for Andrei's work?
Thank you. 😃

**Comment by ribram** [comment]
@eseokoh 
Yes, I would rather commit it after Andrei's work. I will help him wrap things up this week.

**Comment by eseokoh** [comment]
@ribram 
OK.

**Comment by eseokoh** [comment]
@ribram 
Sorry I missed one remark on pgbuf_flush_checkpoint. Please look at page_buffer.c:3358

`
      thread_sleep (0);
`

Since checkpoint jobs is not so urgent, 10 ms may be better than 0. It may consume CPU.

**Comment by ribram** [comment]
@eseokoh 
I have committed the change.

**Comment by eseokoh** [comment]
@ribram 
Great. Thank you.

**Pull request merged**
