### PR TITLE
[CBRD-23922] Add a new TRUNCATE option: CASCADE

### PR DESCRIPTION
**Pull request by wrlawodms**
http://jira.cubrid.org/browse/CBRD-23922

See the Jira issue for more description.

### CODE REVIEW

**Comment by wrlawodms** [comment]
@hornetmj I haven't touched pt_check_truncate() that is for semantic check and pt_apply_truncate(). I thought it is not needed, but I'm not sure. If you think it should be reviewed by the QP maintainer, please request it from him.

**Review by JoohoK — APPROVED** [review]

**Comment by hornetmj** [comment]
@wrlawodms I think that the review by the QA team is not necessary at this moment. Because this is just a start and a small fix(for syntax).

**Comment by wrlawodms** [comment]
@hornetmj Do you mean QP team?

**Review by hornetmj — APPROVED** [review]

**Comment by hornetmj** [comment]
@wrlawodms Sorry. You got it.

**Comment by wrlawodms** [comment]
@hornetmj OK

**Pull request merged**
