### PR TITLE
[CBRD-24169] Remove unused parameters of pgbuf_assign_private_lru

### PR DESCRIPTION
**Pull request by BaekChan1024**
http://jira.cubrid.org/browse/CBRD-24169

Purpose
- Check and refactering,  unused parameters of pgbuf_assign_private_lru function
Implementation
- Remove unused parameters of pgbuf_assign_private_lru function

Remarks
N/A

### CODE REVIEW

**Comment by joohok** [comment]
LGTM
Check code style using indent command as below 
It can be used for '.c' or '.h' file. 
 
`$ indent -l120 -lc120 <file> <file2> `

**Comment by BaekChan1024** [comment]
> LGTM Check code style using indent command as below It can be used for '.c' or '.h' file.
> 
> `$ indent -l120 -lc120 <file> <file2> `

**Comment by wrlawodms** [comment]
@hornetmj As far as I know, in the basic fuzzy checkpoint, all pages until the previous checkpoint are flushed. `prev_chkpt_redo_lsa` in checkpoint interfaces seems to be for it. It is now unused, but I think we should have a discussion to change the interfaces. In my opinion, it's better to only revise `pgbuf_assign_private_lru` here.

**Comment by hornetmj** [comment]
@wrlawodms I got it.

@BaekChan1024 Sorry for the confusion. The comments from @wrlawodms are issues that are currently being discussed internally. I think we need a little more internal discussion. Therefore, only modify pgbuf_assign_private_lru, and restore other modifications.

**Comment by BaekChan1024** [comment]
> @wrlawodms I got it.
> 
> @BaekChan1024 Sorry for the confusion. The comments from @wrlawodms are issues that are currently being discussed internally. I think we need a little more internal discussion. Therefore, only modify pgbuf_assign_private_lru, and restore other modifications.

Then I'll just edit pgbuf_assign_private_lru part. thanks for the review!

**Review by wrlawodms — APPROVED** [review]
Looks good! Thank you for your first contribution. 👍

**Review by hornetmj — APPROVED** [review]

**Review by eido5 — APPROVED** [review]

**Review by joohok — APPROVED** [review]

**Pull request merged**
