### PR TITLE
[CBRD-21693] Repair unload

### PR DESCRIPTION
**Pull request by paulgheorghecristian**
-treat null case for json
-make schema_raw a null value when it doesn't exist

When I read a string after I wrote it as a NULL value, the string's body will be "" (length 0). Is this expected? If so, this is the reason for strlen (db_get_json_schema (val)) > 0 in the code.

### CODE REVIEW

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/object/object_domain.c (1 incorrect indentation(s) found)
```
  3430 	      /* TODO figure why strlen > 0 is required */
```
#### File: src/object/object_primitive.c (5 incorrect indentation(s) found)
```
  2063 	{
  2064 	  value->data.json.json_body = NULL;
  2065 	  value->data.json.document = NULL;
  2066 	  value->data.json.schema_raw = NULL;
  2067 	}
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by ribram** [comment]
@paulgheorghecristian 

Please avoid changing the way json value is stored for backward compatibility. I'd like to fix it when we decide how to serialize the json.

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/object/object_primitive.c (2 incorrect indentation(s) found)
```
 17314 
 17525 
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by paulgheorghecristian** [comment]
@ribram done

**Pull request merged**
