### PR TITLE
[CBRD-24509] Redundant data is sent to Java SP server in method scan

### PR DESCRIPTION
**Pull request by hgryoo**
http://jira.cubrid.org/browse/CBRD-24509

### CODE REVIEW

**Comment by hgryoo** [comment]
I'm considering that maybe we can figure out redundant columns in method scan's list file in advance. In the get_single_tuple() function, they are filtered out, not to read, and assign a null value.

**Comment by hgryoo** [comment]
> I'm considering that maybe we can figure out redundant columns in method scan's list file in advance. In the get_single_tuple() function, they are filtered out, not to read, and assign a null value.

If I filtered out for both C method and Java SP, C method causes regressions. So I've filtered out only for Java SP's argument.

**Review by hyunikn — APPROVED** [review]

**Review by shparkcubrid — APPROVED** [review]

**Review by ctshim — APPROVED** [review]

**Comment by hgryoo** [comment]
I found that after the recent commit 64e4882 is merged, In test_sql, sql/_23_apricot_qa/_00_issues/bug_bts_8166/ tests are extreamly delayed.

**Comment by hgryoo** [comment]
Only cbrd_24482.sql is delayed.

**Comment by hgryoo** [comment]
> Only cbrd_24482.sql is delayed.

The hang is fixed at https://github.com/CUBRID/cubrid-testcases/pull/1317

**Review by beyondykk9 — APPROVED** [review]

**Review by shparkcubrid — APPROVED** [review]

**Review by youngjinj — APPROVED** [review]

**Pull request merged**
