### PR TITLE
[LETS-47] Run scalability unit tests in circle-ci

### PR DESCRIPTION
**Pull request by ribram**
http://jira.cubrid.org/browse/LETS-47

Run the scalability unit tests in circle-ci.

  - Add a script that runs scalability unit tests.
  - Modify circle-ci config file to compile unit tests and run the script during build phase.

The tests included in the script must be very small. No stress/performance tests will be allowed. Any longer unit tests should not be included or should be run in a short version.

### CODE REVIEW

**Comment by ribram** [comment]
@mhoh3963 @hornetmj @ssihil 

Building the scalability unit tests fail on circle-ci. The failure is caused dependency of Catch2, a tool that we added for unit testing, which requires CMake minimum version 3.5.

One possible fix is to upgrade the cmake version in the cubridci/cubridci:develop docker image to 3.5 (or later). Currently it is 2.8. Do you see any problem with doing this?

Another workaround is to create a branch of cubridci with the upgraded CMake version and use that branch instead in the scalability_dev .circle/config.yml.

**Review by mhoh3963 — APPROVED** [review]

**Comment by sjkim777** [comment]
It was decided as the second workaround.
I'll notify you here when the creation of the cubridci docker image for scalability_dev is complete.

**Comment by ribram** [comment]
@sjkim777
Thank you

**Comment by sjkim777** [comment]
@ribram 
It's complete. 
You need to fix the .circle/config.yml. 
`docker:`
 `   - image: cubridci/cubridci:12.0`

**Comment by ribram** [comment]
All unit tests were passed, it took 1 second:

image

**Review by cristiarg — APPROVED** [review]

**Review by adrianbrab — APPROVED** [review]

**Pull request merged**
