### PR TITLE
[CBRD-23557] Do not allow interrupt in DWB wait functions

### PR DESCRIPTION
**Pull request by alexstanro**
http://jira.cubrid.org/browse/CBRD-23545

Do not allow interrupt in DWB wait functions to avoid crash in flush_all.

Checking interruption in flush_all looks dangerous now. I propose to let it as it is, since is legacy.

### CODE REVIEW

**Comment by eseokoh** [comment]
please look into net_server_conn_down. 
It will resume a DWB blocked thread with interrupt.

**Comment by ribram** [comment]
> please look into net_server_conn_down.
> It will resume a DWB blocked thread with interrupt.

If I understand the code correctly, it can only happen if `suspended_p->check_interrupt` is true. If false, interrupt will only be registered in log_tdes and it should be processed later, on the first check.

**Comment by eseokoh** [comment]
yes. You are right.

**Comment by alexstanro** [comment]
@eseokoh 
I still don't see any issue with the fix. Let's think about it. The wait is used only to protect against a shared memory. The shared memory is full, currently used by DWB thread. So, the current thread has to wait for DWB thread to consume the memory. If we enlarge the shared memory enough or remove DWB thread (DWB job moved into the current thread), no wait is needed. So, interrupt will not be catch, like in case of non-DWB. If you think that backup can takes too long, the fix should be done at flush_all. Please, specify clear your concern.

**Pull request merged**
