### PR TITLE
[CBRD-20443] Invalidate snapshot before statement

### PR DESCRIPTION
**Pull request by andrei14vl**
http://jira.cubrid.org/browse/CBRD-20443

The bug was caused by `LC_FETCH_CURRENT_VERSION` that was used to fetch set elements within csql results. 
Before the redesign of mvcc versions, the fetch type was correct as it was indicating the visible version (which was selected before). 

`LC_FETCH_MVCC_VERSION` must be used now, to access the visible version again. 

Applying this change requires that the snapshot should not be invalidated between statement execution and csql results generation. For this purpose, `db_invalidate_mvcc_snapshot_after_statement` was moved before statement execution. I am not sure how safe this is.

### CODE REVIEW

**Comment by ribram** [comment]
@andrei14vl 

#### db_compile_and_execute_queries_internal
Snapshot is invalidate after execution in this function. The invalidation should occur before any compilation phase.

**Comment by ribram** [comment]
@andrei14vl 
Do we need to keep LC_FETCH_CURRENT_VERSION? The conclusion of our discussion was that the routine was required in previous MVCC design when all versions were kept in heap. Once we checked the visibility of an OID, the next fetch on the same OID was guaranteed to be the visible version (so another check was not necessary).

This is no longer true with the new design. Whenever we need to fetch the visible version, we have to go in log and fetch the right version. "Current" would return last version, which is not necessarily same with visible version.

I am considering removing the routine completely.

**Comment by andrei14vl** [comment]
`LC_FETCH_CURRENT_VERSION `is used mostly with classes. 
The exceptions are `cursor_fetch_oids `and `trigger_to_object`.  In this functions it have been also replaced with `LC_FETCH_MVCC_VERSION`.

I am not sure we should remove 'LC_FETCH_CURRENT_VERSION' completely. I will continue to investigate  if the class_oid is transmitted to server as root class oid for this cases, so it can be known on server if a class record was requested. In this case it can be removed, otherwise we should decide how important this information is or may be... :smile:

**Comment by eseokoh** [comment]
@andrei14vl 

Please explain how did it work before refactoring.

**Comment by andrei14vl** [comment]
@eseokoh 
Deleted records were fetched from server with `IS_LOCK `and `LC_FETCH_CURRENT_VERSION`.

Before refactoring, heap_get_class_oid_with_lock was called from xlocator_fetch to get class_oid and also to lock the object. Fetch type was not considered, but the old function `heap_mvcc_check_and_lock_for_delete` was discovering that the object was deleted.

After refactoring, the lock is transformed to `NULL_LOCK `(MVCC object, lock <= `S_LOCK `situation) and the visiblity of the object is not verified when the fetch type is not MVCC. The deleted mvcc records are returned in a non-mvcc manner, as not deleted.

I am not sure however, whether to remove `LC_FETCH_CURRENT_VERSION` completely or keep it for class records (and maybe rename it :smile:).

**Comment by eseokoh** [comment]
@andrei14vl @ribram 

The current patch looks correct. 
What about separating `LC_FETCH_CURRENT_VERSION` issue and merging the fix?

**Comment by andrei14vl** [comment]
@eseokoh 
I updated the patch with a change from `trigger_to_object`. `LC_FETCH_DIRTY_VERSION` seems more appropriate to use for trigger fetch.

Please let me know what do you think and if I can merge the fix as it is, leaving `LC_FETCH_CURRENT_VERSION` modification for other issue.

**Comment by eseokoh** [comment]
@andrei14vl 

OK. The patch for trigger makes sense. 

Would you merge the fix and open an issue for `LC_FETCH_CURRENT_VERSION`?

**Comment by andrei14vl** [comment]
Yes, please find [CBRD-20461](http://jira.cubrid.org/browse/CBRD-20461).
Thank you :smile:

**Pull request merged**
