### PR TITLE
[CBRD-23545] --except-active-log option of backup is obsoleted

### PR DESCRIPTION
**Pull request by alexstanro**
http://jira.cubrid.org/browse/CBRD-23545

### CODE REVIEW

**Comment by ribram** [comment]
1. Please offer details on what happens. It is hard to understand the issue and why prev_lsa page must be included in archive.

2. Is another fix possible? Actually, I am concerned of current logpb_archive_active_log code.
  It has an early out check:
```c
  if (log_Gl.hdr.nxarv_pageid >= log_Gl.hdr.append_lsa.pageid)
    {
      er_log_debug (ARG_FILE_LINE,
		    "log_archive_active_log: WARNING Trying to archive ONLY the append page" " which is incomplete\n");
      return;
    }
```
  But then it stops at prev_lsa.pageid - 1:
```c
  arvhdr->fpageid = log_Gl.hdr.nxarv_pageid;
  last_pageid = log_Gl.append.prev_lsa.pageid - 1;

  if (last_pageid < arvhdr->fpageid)
    {
      last_pageid = arvhdr->fpageid;
    }
```
  Does it help to do no archive if log_Gl.hdr.nxarv_pageid is same as prev_lsa.pageid? Is it safe (a very big log record can cause issues)?

**Comment by alexstanro** [comment]
At backup, all data pages are copied. So, it means that a data page may contain log_Gl.append.prev_lsa. So, we have to be sure that log_Gl.append.prev_lsa is on archive, to correctly recover. No, it doesn't help.

**Comment by eseokoh** [comment]
We need to also consider an alternative: removing e option of backup. In fact, do nothing for the option.
It means backup always includes the current log active. Then, we won’t have this case. 

However, this will push us to another issue. You guys may remember the issue we discussed. When more recent log archive exists, restore not to extract log active from backup. 
I don’t see any other benefit of the option. If i’m correct, maybe better to fix it instead of this case.

**Comment by ribram** [comment]
@eseokoh 

Let's remember the issue, please correct me if something was different. The case was:

  - backup and save all archives and active
  - continue to generate more log and archive volumes
  - stop and remove active log volume.
  - restore from backup; active log is missing, therefore it is copied from backup. archive volumes are not overwritten.
  - !! invalid state: archive volumes contain newer logs than active.

**Comment by alexstanro** [comment]
I think is better to have the option (add archive with few pages in backup rather than whole active volume).

**Comment by eseokoh** [comment]
@ribram 
Yes. Please refer to http://jira.cubrid.org/browse/CBRD-23119 

@alexstanro 
I don't think the option helps except 23119.

**Pull request merged**
