### PR TITLE
[CBRD-20978] Return error for cte.* usage in count function

### PR DESCRIPTION
**Pull request by andrei14vl**
http://jira.cubrid.org/browse/CBRD-20978

According to the comment "the exposed name of a derived table may not be used alone" queries like SELECT count(cte.*) FROM cte should also throw error. 

In this way there will be the same behaviour with CTEs as it is with derived tables.

The only incosistency will appear when the derived table is considered a dummy select and it is folded. Dummy CTEs can not be folded and will return error.

```sql
select count(x.*) from (select * from t1) x;
``` 
-> 
```sql
select count(x.*) from t1 x; --success
```

```sql
with tmp as (select * from t1)select count(tmp.*) from tmp;
```
->
```
ERROR: Class instance reference tmp.* to a derived table name is not allowed.
```

### CODE REVIEW

**Comment by ribram** [comment]
Do you think there are other cases we missed, where CTE must be handled along with info.spec.derived_table?

**Comment by andrei14vl** [comment]
Yes, there are many derived table references where the CTE implications should be reviewed. I propose to open another ticket for this matter.

**Comment by eseokoh** [comment]
I agree with your fix and suggestion :)

**Comment by andrei14vl** [comment]
Please find http://jira.cubrid.org/browse/CBRD-20987.

**Pull request merged**
