### PR TITLE
[CBRD-22152] replication apply

### PR DESCRIPTION
**Pull request by razvanradulescu**
http://jira.cubrid.org/browse/CBRD-22152

### CODE REVIEW

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/base/process_util.c (30 incorrect indentation(s) found)
```
    42 create_child_process (const char *const argv[], int wait_flag, check_funct_t check_func, void *check_arg,
    43 		      const char *stdin_file, char *stdout_file, char *stderr_file, int *exit_status)
   171 	{
   172 	  do
   173 	    {
   174 	      status = WaitForSingleObject (proc_info.hProcess, 10);
   175 	      if (status == WAIT_FAILED)
   176 		{
   177 		  assert (false);
   178 		  return 1;
   179 		}
   180 	      else if (status == WAIT_TIMEOUT)
   181 		{
   182 		  if (check_func (check_arg))
   183 		    {
   184 		      return 1;
   185 		    }
   186 		  continue;
   187 		}
   188 	      else
```
... More than 20 lines are omitted.
#### File: src/base/process_util.h (3 incorrect indentation(s) found)
```
    28 typedef int (*check_funct_t) (void *);
    31 create_child_process (const char *const argv[], int wait_flag, check_funct_t check_func, void *check_arg,
    32 		      const char *stdin_file, char *stdout_file, char *stderr_file, int *exit_status);
```
#### File: src/communication/network_interface_cl.c (1 incorrect indentation(s) found)
```
  3586       request_size += OR_INT_SIZE;	/* desired_tran_index */
```
#### File: src/compat/db_admin.c (6 incorrect indentation(s) found)
```
   887 	{
   888 	  client_credential.desired_tran_index = db_get_override_tran_index ();
   889 	}
   891 	{
   892 	  client_credential.desired_tran_index = NULL_TRAN_INDEX;
   893 	}
```
#### File: src/transaction/boot_cl.c (20 incorrect indentation(s) found)
```
  1449 	{
  1450 	  /* 
  1451 	   * wait for other server request to finish.
  1452 	   * if db_shutdown() is called by signal handler or atexit handler,
  1453 	   * the server request may be running.
  1454 	   */
  1455 	  tran_wait_server_active_trans ();
  1456 
  1457 	  /* 
  1458 	   * Either Abort or commit the current transaction depending upon the value
  1459 	   * of the commit_on_shutdown system parameter.
  1460 	   */
  1461 	  if (tran_is_active_and_has_updated ())
  1464 		{
  1465 		  (void) tran_commit (false);
  1466 		}
  1468 		{
  1469 		  (void) tran_abort ();
  1470 		}
  1472 	}
```
#### File: src/transaction/boot_cl.h (48 incorrect indentation(s) found)
```
    18  */  
    19   

    25  */ 
    26   
    29   
    31   
    34 #endif	/* !WINDOWS */
    35   
    41   
    43 
typedef enum 
    44 { 
BOOT_END_TRANSACTION = 0, 
BOOT_KEEP_TRANSACTION 
    45 } BOOT_CLIENT_TERMINATION_MODE;
    46 

    47 /* Volume assigned for new files/objects  (e.g., heap files) */ 
    48 extern VOLID boot_User_volid;
    51 /* Server host connected */ 
    52 extern char boot_Host_connected[MAXHOSTNAMELEN];
    54 #endif	/* CS_MODE */
    55 
extern int boot_initialize_client (BOOT_CLIENT_CREDENTIAL * client_credential, BOOT_DB_PATH_INFO * db_path_info,
    56 				    
bool db_overwrite, const char *file_addmore_vols, DKNPAGES npages,
```
... More than 20 lines are omitted.
#### File: src/transaction/boot_sr.c (10 incorrect indentation(s) found)
```
  3054       if (tran_index != NULL_TRAN_INDEX && logtb_find_thread_by_tran_index_except_me (tran_index) != NULL)
  3055 	{
  3056 	  logtb_set_current_tran_index (thread_p, tran_index);
  3057 	}
  3059 	{
  3060 	  LOG_SET_CURRENT_TRAN_INDEX (thread_p, LOG_SYSTEM_TRAN_INDEX);
  3061 	  tran_index = NULL_TRAN_INDEX;
  3062 	}
  3068 	logtb_assign_tran_index (thread_p, NULL_TRANID, TRAN_ACTIVE, client_credential, tran_state, client_lock_wait,
  3069 				 client_isolation);
```
#### File: src/transaction/locator_sr.c (91 incorrect indentation(s) found)
```
 13689 locator_prepare_rbr_apply (THREAD_ENTRY * thread_p, const int rbr_operation, OID * class_oid, OID * instance_oid,
 13690 			   RECDES * old_recdes, RECDES * recdes, DB_VALUE * key_value,
 13691 			   HEAP_SCANCACHE * force_scancache);
 13703 locator_repl_apply_rbr (THREAD_ENTRY * thread_p, const char *class_name, const int key_att_id, DB_VALUE * key_value,
 13704 			const std::vector < int >&att_ids, const std::vector < DB_VALUE * >&new_values)
 13762 					  &new_recdes, key_value, &scan_cache);
 13771   for (int i = 0; i < att_ids.size (); i++)
 13775 	{
 13776 	  goto exit;
 13777 	}
 13795     case LC_FLUSH_INSERT:
 13796     case LC_FLUSH_INSERT_PRUNE:
 13797     case LC_FLUSH_INSERT_PRUNE_VERIFY:
 13798       pruning_type = locator_area_op_to_pruning_type ((LC_COPYAREA_OPERATION) rbr_operation);
 13799       error_code =
 13800 	locator_insert_force (thread_p, &hfid, &class_oid, &instance_oid, &new_recdes, has_index,
 13801 			      SINGLE_ROW_INSERT, &scan_cache, &dummy_force_count, pruning_type, NULL, NULL,
 13802 			      UPDATE_INPLACE_NONE);
 13804       if (error_code == NO_ERROR)
 13806 	  /* monitor */
```
... More than 20 lines are omitted.
#### File: src/transaction/log_manager.c (1 incorrect indentation(s) found)
```
  1621 	  assert (false);
```
#### File: src/transaction/transaction_cl.c (950 incorrect indentation(s) found)
```
    18  */  
    19   
    22  */ 
    23   
    25   
    27   
    30 #else	/* !WINDOWS */
    32 #endif	/* !WINDOWS */
    36 #endif	/* 
 */
    38 /* for MAXHOSTNAMELEN */ 
    40 #endif	/* 
 */
    41   
    60   
    63 #endif	/* WINDOWS */
    64 
int tm_Tran_index = NULL_TRAN_INDEX;
    65 
TRAN_ISOLATION tm_Tran_isolation = TRAN_UNKNOWN_ISOLATION;
    66 
bool tm_Tran_async_ws = false;
    67 
int tm_Tran_wait_msecs = TRAN_LOCK_INFINITE_WAIT;
    68 
bool tm_Tran_check_interrupt = false;
    69 
int tm_Tran_ID = -1;
```
... More than 20 lines are omitted.
#### File: src/transaction/transaction_cl.h (55 incorrect indentation(s) found)
```
    18  */  
    19   

    23  */ 
    24   
    27   
    29   
    32 #endif	/* SERVER_MODE */
    33   
    35   
    41   

    49 
typedef enum savepoint_type 
    50 { 
USER_SAVEPOINT = 1, 
SYSTEM_SAVEPOINT = 2 
    51 } SAVEPOINT_TYPE;
    52 

extern int tm_Tran_index;
    53 
extern TRAN_ISOLATION tm_Tran_isolation;
    54 
extern bool tm_Tran_async_ws;
    55 
extern int tm_Tran_wait_msecs;
    56 
extern int tm_Tran_ID;
    57 
extern bool tm_Tran_check_interrupt;
    58 
extern bool tm_Use_OID_preflush;
```
... More than 20 lines are omitted.
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/transaction/locator_sr.c (2 incorrect indentation(s) found)
```
 13915 			const char *statement)
 13926   snprintf (db_user_str, sizeof (db_user_str) - 1, "-u%s", db_user);
```
#### File: src/transaction/locator_sr.h (1 incorrect indentation(s) found)
```
   121 				   const char *statement);
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/transaction/locator_sr.c (2 incorrect indentation(s) found)
```
 13915 			const char *statement)
 13926   snprintf (db_user_str, sizeof (db_user_str) - 1, "-u%s", db_user);
```
#### File: src/transaction/locator_sr.h (1 incorrect indentation(s) found)
```
   121 				   const char *statement);
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/transaction/locator_sr.c (3 incorrect indentation(s) found)
```
 13636 			const int key_att_id, DB_VALUE * key_value,
 13914 			const char *statement)
 13925   snprintf (db_user_str, sizeof (db_user_str) - 1, "-u%s", db_user);
```
#### File: src/transaction/locator_sr.h (3 incorrect indentation(s) found)
```
   121 				   const char *statement);
   123 				   const int key_att_id, DB_VALUE * key_value,
   124 				   const std::vector < int >&att_ids, const std::vector < DB_VALUE * >&new_values);
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/transaction/locator_sr.c (30 incorrect indentation(s) found)
```
 13622 			   OID * instance_oid, RECDES * old_recdes, RECDES * recdes, DB_VALUE * key_value,
 13636 			const int key_att_id, DB_VALUE * key_value,
 13637 			const std::vector < int >&changed_att_ids, const std::vector < DB_VALUE > &new_values,
 13638 			const RECDES * new_recdes_arg)
 13680 	      || rbr_operation == LC_FLUSH_INSERT_PRUNE_VERIFY);
 13687 	{
 13688 	  attr_info_inited = true;
 13689 	  goto exit;
 13690 	}
 13694 	{
 13695 	  goto exit;
 13696 	}
 13703 	{
 13704 	  goto exit;
 13705 	}
 13711 	{
 13712 	  error_code = heap_attrinfo_set (NULL, changed_att_ids[i], &(new_values[i]), &attr_info);
 13713 	  if (error_code != NO_ERROR)
 13717 	}
 13721 	{
```
... More than 20 lines are omitted.
#### File: src/transaction/locator_sr.h (4 incorrect indentation(s) found)
```
   121 				   const char *statement);
   123 				   const char *class_name, const int key_att_id, DB_VALUE * key_value,
   124 				   const std::vector < int >&changed_att_ids,
   125 				   const std::vector < DB_VALUE > &new_values, const RECDES * new_recdes_arg);
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by razvanradulescu** [comment]
Obsolete

**Pull request closed without merging**
