### PR TITLE
[CBRD-20453] Fixing GCC5 compatibility issues

### PR DESCRIPTION
**Pull request by rimio**
This PR contains code that fixes build issues for GCC5. Build was tested (and works) for version 5.3.0.

**1. libgpg-error**

Library's makefile uses gcc preprocessor to generate error codes. Because of a change in gcc defaults, we must now specify that we want to supress linemarkers (-P) in order to have the awk script run correctly.

Alternative would be to keep library source intact and write a patch which we apply at build time, but this may add unnecessary complexity as well as dependencies (*patch* tool).

Testing for gcc ver <5 would be nice.

Issue: https://lists.gnupg.org/pipermail/gnupg-devel/2015-March/029588.html
Docs: https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html#Preprocessor-Options

**2. Linking math library**

We are now explicitly specifying the *math* library dependency for a few targets. This change may be caused by other changes in glibc? I'm running 2.23.

Testing for Windows build would be nice.

### CODE REVIEW

**Comment by rimio** [comment]
Fixed Windows build for math library dependency issue.

**Comment by eseokoh** [comment]
@rimio 

Would you apply the fix to libgpg to `Makefile.am`?

We are also considering to remove libgpg from our external and use system library. 
It will be dealt with a separated issue.

**Comment by rimio** [comment]
@eseokoh 

I've pushed the modification. While a correct decision, the build system does not call automake on libgpg-error, but uses the *Makefile.in* file provided.

**Comment by eseokoh** [comment]
@rimio 

Would you merge the fix?
Thanks for your contribution. 😃

**Comment by rimio** [comment]
@eseokoh 

Done. No problem :).

**Pull request merged**
