### PR TITLE
[CBRD-20538] Inline perfmon_is_perf_tracking and perfmon_id_perf_tracking and acti…

### PR DESCRIPTION
**Pull request by asturzu**
http://jira.cubrid.org/browse/CBRD-20538

Inline perfmon_is_perf_tracking and perfmon_is_perf_tracking_and_active and remove some useless
variables and assignments.

### CODE REVIEW

**Comment by eseokoh** [comment]
@asturzu 

I'm sorry it does not help. I make a release build and the functions are not inlined:
```
% nm libcubrid.so | grep perfmon_is_perf_tracking
00000000000f8380 T perfmon_is_perf_tracking
00000000000fc2b0 T perfmon_is_perf_tracking_and_active
% nm libcubrid.so | grep perfmon_add_stat_at_offset
% 
```
Please notice that static inline functions like `perfmon_add_stat_at_offset` are properly inlined. 
I don't know it works with visual studio. 

I try forced inline option and gcc raises unimplemented error:
```
/home1/beatrice/workspace/myfork/src/base/perf_monitor.h:608: sorry, unimplemented: inlining failed in call to 'perfmon_is_perf_tracking': function body not available
/home1/beatrice/workspace/myfork/src/query/vacuum.c:1109: sorry, unimplemented: called from here
make[2]: *** [sa/CMakeFiles/cubridsa.dir/__/src/query/vacuum.c.o] Error 1
make[1]: *** [sa/CMakeFiles/cubridsa.dir/all] Error 2
```

**Comment by eseokoh** [comment]
@asturzu 

I'm sorry it does not work to me. gcc returns the same unimplemented error. 
Please try to make a release build. 

I think we have to replace the INLINE functions as macros.

**Comment by asturzu** [comment]
Yes,

I was compiling with debug mode. I will try with release.

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/base/porting.h (5 incorrect indentation(s) found)
```
   138 #endif				/* !_MSC_VER || _MSC_VER < 1700 */
   498 #endif				/* _MSC_VER && _MSC_VER < 1800 */
   542 #endif				/* !_MSC_VER || _MSC_VER < 1800 */
   588 #endif				/* _MSC_VER && _MSC_VER >= 1900 && !_CRT_NO_TIME_T */
   596 #endif				/* !_TIMESPEC_DEFINED */
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Comment by eseokoh** [comment]
@asturzu 

Great. I've confirmed it works. :)
What about trying to also inline `perfmon_time_stat` and `perfmon_get_activation_flag` functions?

**Comment by asturzu** [comment]
Sounds good. I'll make them inline.

**Pull request merged**
