### PR TITLE
[CBRD-24068] Add an option of the unloaddb that enables unloading data only in data volumes

### PR DESCRIPTION
**Pull request by wrlawodms**
http://jira.cubrid.org/browse/CBRD-24068

### CODE REVIEW

**Comment by hornetmj** [comment]
@wrlawodms github-checks complains the code_style. Please check it.

**Comment by wrlawodms** [comment]
@hornetmj It's not from this PR.

**Review by joohok — APPROVED** [review]

**Comment by hornetmj** [comment]
@wrlawodms Is this cherry-pick?

**Comment by wrlawodms** [comment]
@hornetmj Yes. It had a conflict in the `msg/de_DE.utf8/utils.msg`, though.

**Review by hornetmj — APPROVED** [review]

**Pull request merged**
