### PR TITLE
[CBRD-20588] Fix differences between DB_GET_* and DB_MAKE_* functions and macros

### PR DESCRIPTION
**Pull request by lucianlazar2211**
http://jira.cubrid.org/browse/CBRD-20588

This is a work in progress. I have opened the PR in order to have an easier discussion based on this topic.

- [x] Refactor DB_GET_* macros

- [x] Refactor DB_MAKE_* macros

- [x] Write investigation results in JIRA issue

- [ ] Fix compile warnings

- [x] Fix differences between `dbtype.h` and `dbi_compat.h`

### CODE REVIEW

**Comment by eseokoh** [comment]
I'd like to propose to investigate the differences between functions and macros first.
If we don't clearly understand the behavior difference, we may suffer unexpected troubles when we inline the functions.

**Comment by lucianlazar2211** [comment]
Many compilation warnings for now, due to bad order of header inclusions. I am currently investigating this issue.

**Comment by cubridci** [comment]
Build comment file: 
--------------
--------------
**Please check T_CCI_CUBRID_STMT in src/cci/cas_cci.h and CUBRID_STMT_TYPE in src/compat/dbi_compat.h

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
--------------
**Please check T_CCI_CUBRID_STMT in src/cci/cas_cci.h and CUBRID_STMT_TYPE in src/compat/dbi_compat.h

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
--------------
**Please check T_CCI_CUBRID_STMT in src/cci/cas_cci.h and CUBRID_STMT_TYPE in src/compat/dbi_compat.h

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
--------------
**Please check T_CCI_CUBRID_STMT in src/cci/cas_cci.h and CUBRID_STMT_TYPE in src/compat/dbi_compat.h

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
--------------
**Please check T_CCI_CUBRID_STMT in src/cci/cas_cci.h and CUBRID_STMT_TYPE in src/compat/dbi_compat.h

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
--------------
**Please check T_CCI_CUBRID_STMT in src/cci/cas_cci.h and CUBRID_STMT_TYPE in src/compat/dbi_compat.h

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
--------------
**Please check T_CCI_CUBRID_STMT in src/cci/cas_cci.h and CUBRID_STMT_TYPE in src/compat/dbi_compat.h

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
--------------
**Please check T_CCI_CUBRID_STMT in src/cci/cas_cci.h and CUBRID_STMT_TYPE in src/compat/dbi_compat.h

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
--------------
**Please check T_CCI_CUBRID_STMT in src/cci/cas_cci.h and CUBRID_STMT_TYPE in src/compat/dbi_compat.h

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
--------------
**Please check T_CCI_CUBRID_STMT in src/cci/cas_cci.h and CUBRID_STMT_TYPE in src/compat/dbi_compat.h

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
--------------
**Please check T_CCI_CUBRID_STMT in src/cci/cas_cci.h and CUBRID_STMT_TYPE in src/compat/dbi_compat.h

--------------

**Comment by cubridci** [comment]
Build comment file: 
--------------
#### File: src/compat/dbi_compat.h (2 incorrect indentation(s) found)
```
  2066 DB_DEFAULT_CURR_USER = 6
  2073   extern void db_date_decode (const DB_DATE * date, int *monthp, int *dayp, int *yearp);
```
--------------
**Please run 'indent -l120 -lc120' to correct the indentation**

--------------

**Pull request closed without merging**
