### PR TITLE
[CBRD-23142] Builds infrastructure for group commit

### PR DESCRIPTION
**Pull request by alexstanro**
http://jira.cubrid.org/browse/CBRD-23142

### CODE REVIEW

**Comment by ribram** [comment]
Patch is still too big, please split it even further. One options is to separate by type of complete manager: master, single, slave. First patch could be be master+common parts (group complete virtual interface & log_impl)

Detailed description on each patch is also required to help reviewers understand the implementation.

**Comment by alexstanro** [comment]
Does everyone feel the need to split again in master, slave, single ? 
I did this initially, unfortunately without CR.

**Comment by ribram** [comment]
Please allow me bring arguments why is better to split the patch into smallest units possible:

  1. it is easier for add detailed explanations on each unit, rather on the whole patch
  2. it is easier for everyone to keep the discussions focused; in a big patch, many threads of discussions are open and it is hard to keep track of every detail
  3. scheduling 30 minutes - 1 hour reviews makes it easier to prioritize it. it is hard to review if it takes 3-4 hours or more.
  4. since HA is not scheduled for 10.2 it is preferable to make step-by-step careful reviews to merging the big patch first and then changing things.

As a note to 4). we have been often tempted in the past to go with merging big patches and then gradually fix issues, but it proved to be a problematic approach. Reviews have not been focused on details and missed many issues and it then takes months to discover and fix everything.

**Comment by ribram** [comment]
@other reviewers, please add an answer with your preference for Alex's question.

**Comment by razvanradulescu** [comment]
I also think the patch is too large for having a review in a reasonable time.
Regardless of the form, I need an explanation on the contents of PR.

**Comment by alexstanro** [comment]
Infrastructure means adding single, slave, master, GC - classes, methods (and related where I didn't find another quick solution) without creating/calling objects/methods. I thought that is obvious.

**Comment by radudoros** [comment]
I think we all would like smaller PRs, I would also like this PR to be split further. However, I don't know exactly how to rate the tradeoff between the potential headache of splitting it and the ease of reviewing...

**Comment by alexstanro** [comment]
Radu's point of view is correct.

**Pull request closed without merging**
