### PR TITLE
[CBRD-22195] Add schema changes and grammar for new online option

### PR DESCRIPTION
**Pull request by lucianlazar2211**
http://jira.cubrid.org/browse/CBRD-22195

I have added the required schema changes and the grammar needed for the new online option of creating index starting from @eseokoh 's branch.
However, the new online option will create only an empty index file, without loading in it any existing information. I left it as a `TODO:` until I write the Index Builder, probably in a separate PR.

### CODE REVIEW

**Comment by eseokoh** [comment]
The current regression failures are expected:
* medium: 3
* sql: 102

**Comment by eseokoh** [comment]
@lucianlazar2211 

I'd like to make codes more robust:
* not allow FK to change its status 
* not allow non-index constraint (e.g, not null/null) to  change its status
* not allow a local index of a partition table to change its status (We will only allow partitioned tables and ordinary tables)

**Comment by lucianlazar2211** [comment]
@eseokoh 
Does this mean that local indexes on partitions should always be created with the `SM_NORMAL_INDEX` label?

**Comment by eseokoh** [comment]
@lucianlazar2211 

I was bad. The current code already treats the case.
please look into my changes.

**Pull request merged**
