### PR TITLE
[CBRD-21621] VS 2012 does not support <chrono>.

### PR DESCRIPTION
**Pull request by eseokoh**
http://www.jira.cubrid.org/browse/CBRD-21621

Quick fix for CI build.

### CODE REVIEW

**Comment by eseokoh** [comment]
Unfortunately, it is not enough. 

```
15:34:52   c:\build\windows-64-release-1259\cubrid-10.2.0.7708-9abb84e\unit_tests\common\test_timers.hpp(27): fatal error C1083: Cannot open include file: 'chrono': No such file or directory [C:\build\WINDOWS-64-release-1259\cubrid-10.2.0.7708-9abb84e\build_Release_x64\unit_tests\common\test_common.vcxproj]
```

@ribram @bsolomenco 

I'm considering to temporarily disable unittests of Windows until CI system upgrades to VS 2017.
What do you think?

**Comment by bsolomenco** [comment]
Hi!

I was just writing you about this
Timing is not important (yet) for string_buffer tests. I can completely
remove <chrono>
But for the rests of tests it is, there are specific tests for performance
made by Remzi

To disable all unit tests, the UNIT_TESTS should not be defined

Regards,
Bogdan

**Comment by ribram** [comment]
I think we can correct slip from Bogdan's patch and disable unit test for CI.

**Comment by eseokoh** [comment]
Then, can you please fix these with the current issue?

**Pull request merged**
